# openapi2-functions.yaml
swagger: '2.0'
info:
  title: ticket-automation-api-spec
  description: API specification for ticket-automation-application
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /incident:
    post:
      summary: Incident alert
      operationId: incident-alert
      x-google-backend:
        address: {INCIDENT_CLOUDFUNCTION_URL}
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /request:
    post:
      summary: Request alert
      operationId: request-alert
      x-google-backend:
        address: {REQUEST_CLOUDFUNCTION_URL}
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /crm:
    post:
      summary: Payload check
      operationId: payload-check
      x-google-backend:
        address: {PAYLOAD_TEST_CLOUDFUNCTION_URL}
      security:
      - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"

